name: Build and test on PR
on:
  pull_request:
    branches:
      - 'main'
      - '3.*'
  workflow_dispatch:

jobs:
  build:
    name: Build container images
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker common actions
        uses: ./.github/actions/docker-common
        with:
          platforms: linux/amd64
          push: false
