name: Build Release
on:
  push:
    branches:
      - 'main'
      - '3.*'
    tags:
      - 'v3.*'
  workflow_dispatch:
jobs:
  build:
    name: Build release container images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker common actions
        uses: ./.github/actions/docker-common
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          docker_hub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker_hub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          ghcr_token: ${{ secrets.GITHUB_TOKEN }}
